### ISSUE TITLE
trasformare "Incidenti passati" in "incidenti aperti"?

### ISSUE THREAD

**Issue by brancomat** [edigiacomo/django-statusboard#32]
So che cambio idea più velocemente di trump, però pistolandoci mi sono accorto di ciò:
l'incidente di schioppo condizionatori, se lo metto con la sua data vera (10 febbraio o giù di lì senza aggiornamenti degni di nota) viene fiondato in archivio o in ogni caso gli passa davanti l'incidente (chiuso!) sui webservice.

Quindi per sanità mentale (e visto che se no ti annoi) si potrebbe trasformare la sezione di incidenti nella pagina principale in modo che mostri solo gli incidenti che non hanno stato "risolto" (che uno poi può andarsi a consultare nella parte dell'archivio dove manterrei l'ordinamento attuale).

Però parliamone (vedi label: question)

**Comment by edigiacomo** [comment]
Sarebbe meglio definirli "Incidenti recenti" in quanto sono quelli avvenuti negli ultimi N giorni (configurabile, default: 7).

Il fatto che siano chiusi o meno non credo dovrebbe influire sulla loro visibilità.

**Comment by edigiacomo** [comment]
Uh non avevo visto il corpo della issue ma solo il titolo (o hai editato? Boh, vabbé). Forse avrebbe senso usare come data l'ultimo update - e se un problema va avanti per più degli ultimi N giorni, magari un aggiornamento sarebbe comunque sensato (e in quel modo si aggiorna anche la data).

In alternativa - oppure in aggiunta - gli incidenti non risolti stanno sempre nella home page.

**Comment by brancomat** [comment]
Uhm, no non avevo editato, ho creato la issue completa, boh.

Comunque sì, la soluzione di tenere sempre in home page gli incidenti non risolti e lasciare l'archivio cronologico al momento è quella che mi piace di più.
Poi è chiaro che un incident per restare aperto tanto tempo avrà necessariamente degli aggiornamenti (tipo: le ottocento mail con i tecnici dei condizionatori) però una cosa è poterli fare una cosa è doverli fare per mantenere la visibilità del problema, non so.

**Comment by edigiacomo** [comment]
Per archivio cronologico intendi che l'incidente viene messo nel giorno in cui avviene e non nel giorno dell'ultimo aggiornamento?

Mi era arrivata prima la mail (vuota) con l'assegnazione del bug che quella con il bug :|

**Comment by brancomat** [comment]
No, così com'è ora... riassumo proposta ideale (per me):

- modificare la sezione interventi della pagina principale visualizzando solo quelli non risolti
- lasciare l'archivio interventi così com'è

**Comment by edigiacomo** [comment]
Aggiungo opzione per visualizzare tutti gli incidenti non chiusi (e.g.`OPEN_INCIDENT_IN_INDEX = True`) e con `INCIDENT_DAYS_IN_INDEX = 0` hai il comportamenti richiesto. Che dici?

Preciso che ogni incidente è visualizzato nel giorno in cui è accaduto (`Incident.occurred`).

**Comment by brancomat** [comment]
:+1:

**Comment by edigiacomo** [comment]
Il branch issues/32 contiene la fix. Tuttavia, mi è venuto un dubbio:
il filtro per controllare se un incidente è aperto o meno è abbastanza
naif, in quanto considera aperto un incidente se non contiene un
aggiornamento con status "Risolto". Ma se "riapro" un incidente (i.e.
aggiungo un aggiornamento con status diverso da "Risolto") il filtro lo
considera ormai chiuso.

Vorrei risolvere la cosa in maniera trasparente per l'utente, ma per ora
ce lo teniamo così. Considero chiusa questa issue e ne apro un'altra.

Close #32.

**Comment by edigiacomo** [comment]
> No, così com'è ora... riassumo proposta ideale (per me):
>
> - modificare la sezione interventi della pagina principale visualizzando solo quelli non risolti
> - lasciare l'archivio interventi così com'è

Per avere il comportamento richiesto la configurazione deve essere

```python
STATUSBOARD = {
    "INCIDENT_DAYS_IN_INDEX": 0,
    "OPEN_INCIDENT_IN_INDEX": True,
}
```
