### ISSUE TITLE
Incidente associato a più servizi?

### ISSUE THREAD

**Issue by edigiacomo** [edigiacomo/django-statusboard#34]
Mi faccio e ti faccio una domanda: oggi, con il casino dei modelli mancanti, ho creato un incidente e l'ho associato a COSMO-i7. Tuttavia, sarebbe stato corretto associarlo anche a COSMO-i2.

La domanda nasce spontanea: sarebbe più sensato associare un incidente a più servizi. Questo tuttavia appesantirebbe un po' l'interfaccia, in quanto si avrebbe una etichetta per ogni servizio coinvolto.
L'unico modo per smorzare che mi viene in mente è mettere le etichette sotto al titolo dell'incidente.

**Comment by brancomat** [comment]
Ok per etichetta sotto magari togliendo informazioni sul tempo ("avvenuto...") che è un po' ridondante
