### ISSUE TITLE
Maintenance messages should be published until closed

### ISSUE THREAD

**Issue by edigiacomo** [edigiacomo/django-statusboard#44]
Now, a maintenance message is removed from the page when its scheduled time elapses. However, the message is useful during the maintenance too.

Proposal: add a "completed" `BooleanField` to the Maintenance model (and a "completion_time" `DateTimeField`). Only the open maintenances  will be published:

```python
maintenance_messages = Maintenance.objects.filter(completed=False)).order_by('scheduled`)
```

**Comment by brancomat** [comment]
I don't know how difficult would be to implement this, but:
"completion_time" could be also an (optional) entry of the Maintenance model similar to the "planned" field so the maintenance message could either be manually flagged as completed or automatically expire after a given time.

**Comment by edigiacomo** [comment]
True, I considered this option too, but I think I'd prefer to forget to close a completed maintenance than have to think about extending the completion time while I'm fighting against a maintenance that is longer than expected (never happened, of course :grimacing: )

The estimated time of completion can be in the description of the maintenance, e.g. "The estimated time of completion is 2018-08-30 03:00 UTC."

**Comment by brancomat** [comment]
ok, I just thought that forgetting to close the maintenance could be a far more common scenario than having to extend an optional completion time, but no problem

**Comment by edigiacomo** [comment]
I disagree (see my last mainteinance mail), but anyway I think is a more cautious approach.

**Comment by edigiacomo** [comment]
Well, maybe you're not the only fearless and brave out there, so I can add an optional field "close_at" to automatically remove the expired maintenances:

```python
query = Q(completed=False) | ( Q(close_at__isnull=False) & Q(close_at__gt=now() )

maintenances = Maintenance.objects.filter(query)
```

I could add a message to inform that the maintenance message will be automatically removed at the given time.

**Comment by edigiacomo** [comment]
I decided to keep things simple: a maintenance message is a notice about an imminent maintenance and it should be removed when it starts.

An incident can be created to keep track of the maintenance status and the same incident is closed when the operation ends.
