### ISSUE TITLE
Split maintenance time (start + finish)

### ISSUE THREAD

**Issue by brancomat** [edigiacomo/django-statusboard#49]
Maintenance time now has only one field (the scheduled beginning of the maintenance)

It could be useful to split in two fields:
starting time and expected finished time automatically changing the warning message and color from "planned" to "ongoing"

**Comment by edigiacomo** [comment]
I just realized that we already talked about this issue (#44).

But since this problem was raised again, we can rediscuss this feature.

**Comment by brancomat** [comment]
Ok :)
We can keep it like this to keep things simple, the only thing I'd change is the "planned" label with something like "planned start" to clarify a bit.

If we want to avoid to open another issue in 15 months, maybe we could add a sort of help to the `mantainance/create` page defining its scope with a couple of lines:

> Mantaineance messages are meant as an alert __before__ an event.
> Any failure due to the maintenance should be filed in a separate Incident

or, as the closing message of #44 stated:
> A maintenance message is a notice about an imminent maintenance and it should be removed when it starts.
> An incident can be created to keep track of the maintenance status and the same incident is closed when the operation ends.

**Comment by edigiacomo** [comment]
From branch `issues/49`:

![image](https://user-images.githubusercontent.com/927277/74365760-ff4c1780-4dce-11ea-86b5-701cb76b2fb1.png)
![image](https://user-images.githubusercontent.com/927277/74365836-2276c700-4dcf-11ea-9f1e-4c0422674df7.png)
![image](https://user-images.githubusercontent.com/927277/74365904-420def80-4dcf-11ea-8d40-fc75d158e7d5.png)
![image](https://user-images.githubusercontent.com/927277/74365918-4afec100-4dcf-11ea-9852-8e1fa7f56eb3.png)

**Comment by edigiacomo** [comment]
Sorry, the last one is
![image](https://user-images.githubusercontent.com/927277/74366353-29eaa000-4dd0-11ea-9498-505753109acb.png)

**Comment by brancomat** [comment]
perfect!
