### ISSUE TITLE
Release 0.13 contains .woff files from Bootstrap, of 0 bytes length

### ISSUE THREAD

**Issue by cghirelli** [edigiacomo/django-statusboard#65]
![zero_lenght](https://github.com/user-attachments/assets/dd7d3cd2-cd5d-426a-ba30-c6c403d6702e)

**Comment by edigiacomo** [comment]
Thanks @cghirelli! The problem was fixed in 001d4485b9802a246818cbe3f7f71c10b10b930e, I'll release a new version of the module as soon as possible.
